CrudML/CrudML/Models/ViewModels/TablaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Linq;
using System.Web;

namespace CrudML.Models.ViewModels
{
    public class TablaViewModel
    {
        [Required]
        [StringLength(50)]
        [Display(Name = "Tipo de documento:")]
        public string tipo_documento { get; set; }
        [Required]
        [IntegerValidator]
        [Display(Name ="Número de identificación")]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name ="Nombre")]
        public string Nombre { get; set; }
        
        
        [StringLength(50)]
        [Display(Name = "Direccion")]
        public string direccion { get; set; }
        [Required]
        [IntegerValidator]
        [Display(Name = "Telefono")]
        public string telefono { get; set; }
        
        [EmailAddress]
        [Display(Name = "Correo electrónico")]
        public string correo { get; set; }
        
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de creacion")]
        public DateTime? fecha_creacion { get; set; }
    }
}

CrudML/CrudML/Controllers/TablaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrudML.Models;
using CrudML.Models.ViewModels;

namespace CrudML.Controllers
{
    public class TablaController : Controller
    {
        // GET: Tabla
        public ActionResult Index()
        {
            List<ListTablaViewModel> lst;
            using(productoEntities db=new productoEntities())
            
                {
                 lst= (from d in db.crudcreate
                            select new ListTablaViewModel
                         {
                            Id = d.id,
                            Nombre=d.nombre_cliente,
                            tipo_documento=d.tipo_documento,    
                            direccion=d.direccion,
                            telefono=d.telefono,
                            correo=d.correo,    
                            fecha_creacion=d.fecha_creacion,    

                         }).ToList();
                }
            return View(lst);
        }
        public ActionResult Nuevo() 
        {
            return View();

        }
        [HttpPost]
        public ActionResult Nuevo(TablaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (productoEntities db = new productoEntities())
                    {
                       db.SPINSERT1(model.Id, model.Nombre, model.tipo_documento, model.direccion, model.telefono, model.correo, model.fecha_creacion);
                       
                        
                        db.SaveChanges();
                          

                    }
                    return Redirect("~/Tabla/");
                }
                return View(model);
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
            
        }
        public ActionResult Editar(int Id)
        {
            TablaViewModel model = new TablaViewModel();
            using (productoEntities db= new productoEntities())
            {
                var oTabla = db.crudcreate.Find(Id);
                model.tipo_documento=oTabla.tipo_documento;
                model.Nombre=oTabla.nombre_cliente;
                model.direccion=oTabla.direccion;
                model.telefono = oTabla.telefono;
                model.correo = oTabla.correo;
                model.fecha_creacion=oTabla.fecha_creacion;
                model.Id = oTabla.id;

            }
                return View(model);

        }
        [HttpPost]
        public ActionResult Editar(TablaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (productoEntities db = new productoEntities())
                    {
                        db.SPUPDATE1(model.Id, model.Nombre, model.tipo_documento, model.direccion, model.telefono, model.correo, model.fecha_creacion);
                        db.SaveChanges();


                    }
                    return Redirect("~/Tabla/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }
        [HttpGet]
        public ActionResult Eliminar(int Id)
        {
            
            using (productoEntities db = new productoEntities())
            {
                db.SPDELETE1(Id);
                
                db.SaveChanges();
            }
            return Redirect("~/Tabla/");

        }
    }
}

CrudML/CrudML/Views/Tabla/Editar.cshtml
@model CrudML.Models.ViewModels.TablaViewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Editar", "Tabla", FormMethod.Post))
{
    
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.Id)
            <div>
                @Html.LabelFor(d => d.tipo_documento)<br />

                <pre>@Html.Label("CC") @Html.RadioButtonFor(d => d.tipo_documento, "CC", true)   @Html.Label("TI") @Html.RadioButtonFor(d => d.tipo_documento, "TI", true)  </pre>
                @Html.ValidationMessageFor(d => d.tipo_documento, null, new { @class = "red" })<br />
            </div>
            <div>
                @Html.LabelFor(d => d.Id)
                @Html.TextBoxFor(d => d.Id, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Id, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>
            <div>

                @Html.LabelFor(d => d.direccion)
                @Html.TextBoxFor(d => d.direccion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.direccion, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.telefono)
                @Html.TextBoxFor(d => d.telefono, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.telefono, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.correo)
                @Html.TextBoxFor(d => d.correo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.correo, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.fecha_creacion)<br />
                @Html.EditorFor(d => d.fecha_creacion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.fecha_creacion, null, new { @class = "red" })
            </div>







            <br />
            <div style="text-align:center;">
                <input value="Guardar" class="btn btn-primary" type="submit" style="background-color: #191970" />
            </div>
        </div>

    </div>
}

CrudML/CrudML/Views/Tabla/Index.cshtml
@model List<CrudML.Models.ViewModels.ListTablaViewModel>

@{
    ViewBag.Title = "Clientes";
}

<h1 style="font: italic; font-size: x-large; text-align: center; width: 800px; color: #191970 ">@ViewBag.Title</h1>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#Id</th>
                <th>Nombre</th>
                <th>tipocc</th>
                <th>direccion</th>
                <th>telefono</th>
                <th>Correo</th>
                <th>fecha</th>
                <th>Editar/Eliminar</th>

            </tr>
            @foreach(var Elemento in Model)
            {
                <tr> 
                    
                    <td>@Elemento.Id</td>
                    <td>@Elemento.Nombre</td>
                    <td>@Elemento.tipo_documento</td>
                    <td>@Elemento.direccion</td>
                    <td>@Elemento.telefono</td>
                    <td>@Elemento.correo</td>
                    <td>@Elemento.fecha_creacion</td>
                    <td>
                        <a class="btn btn-default" href="~/Tabla/Editar/@Elemento.Id">Editar</a>
                        <a class="btn btn-danger" href="~/Tabla/Eliminar/@Elemento.Id" style="background-color: #191970">Eliminar</a>
                    </td>
                </tr>
            }
        </table>
    </div>

</div>

<div class="row" style="text-align: center;width:800px">
    <a href="~/Tabla/Nuevo" class="btn btn-primary" style="background-color: #191970">Agregar nuevo cliente</a>

</div>

CrudML/CrudML/Views/Tabla/Nuevo.cshtml
@model CrudML.Models.ViewModels.TablaViewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Nuevo", "Tabla", FormMethod.Post))
{
<div class="row">
    <div class="col-md-12">
        <div>
            @Html.LabelFor(d => d.tipo_documento)<br />

            <pre>@Html.Label("CC") @Html.RadioButtonFor(d => d.tipo_documento, "CC", true)   @Html.Label("TI") @Html.RadioButtonFor(d => d.tipo_documento, "TI", true)  </pre>  
            @Html.ValidationMessageFor(d => d.tipo_documento, null, new { @class = "red" })<br />
        </div>
        <div>
            @Html.LabelFor(d => d.Id)
            @Html.TextBoxFor(d => d.Id, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Id, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.Nombre)
            @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
        </div>
        <div>

            @Html.LabelFor(d => d.direccion)
            @Html.TextBoxFor(d => d.direccion, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.direccion, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.telefono)
            @Html.TextBoxFor(d => d.telefono, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.telefono, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.correo)
            @Html.TextBoxFor(d => d.correo, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.correo, null, new { @class = "red" })
        </div>

        <div>
            @Html.LabelFor(d => d.fecha_creacion)<br />
            @Html.EditorFor(d => d.fecha_creacion, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.fecha_creacion, null, new { @class = "red" })
        </div>



        
        
       
        
        <br />
        <div style="text-align:center;">
            <input value="Guardar" class="btn btn-primary" type="submit" style="background-color: #191970" />
        </div>
    </div>

</div>
}